const trashData = {
    organic: {
        originImgSrc: "../image/recycle/organic/trash-origin.PNG",
        originName: "음식물 쓰레기",
        trashcanImgSrc: "../image/recycle/organic/trash-can.PNG",
        selectBtn1Txt: "사료화",
        selectBtn2Txt: "비료화",
        step1_1: "살균·건조 처리",
        step1_2: "발효",
        step1_3: "배합",
        step1_4: "사료",
        step2_1: "석회 안정화",
        step2_2: "발효",
        step2_3: "건조",
        step2_4: "비료"
    },
    paper: {
        originImgSrc: "../image/recycle/paper/trash-origin.PNG",
        originName: "종이 쓰레기",
        trashcanImgSrc: "../image/recycle/paper/trash-can.PNG",
        selectBtn1Txt: "박스",
        selectBtn2Txt: "신 제품",
        step1_1: "수거",
        step1_2: "세척 및 분쇄",
        step1_3: "펄프 제조",
        step1_4: "새 박스",
        step2_1: "해리공정",
        step2_2: "정선공정",
        step2_3: "건조 및 농축",
        step2_4: "재활용 상품"
    },
    glass: {
        originImgSrc: "../image/recycle/glass/trash-origin.PNG",
        originName: "유리 쓰레기",
        trashcanImgSrc: "../image/recycle/glass/trash-can.PNG",
        selectBtn1Txt: "반복사용병",
        selectBtn2Txt: "1회용 병",
        step1_1: "수거",
        step1_2: "세척 및 멸균",
        step1_3: "음료 담기",
        step1_4: "포장 및 출하",
        step2_1: "색상 선별",
        step2_2: "분쇄 및 가공",
        step2_3: "유리공정",
        step2_4: "재활용 상품"
    },
    plastic: {
        originImgSrc: "../image/recycle/plastic/trash-origin.PNG",
        originName: "플라스틱 쓰레기",
        trashcanImgSrc: "../image/recycle/plastic/trash-can.PNG",
    },
    metal: {
        originImgSrc: "../image/recycle/metal/trash-origin.PNG",
        originName: "캔 쓰레기",
        trashcanImgSrc: "../image/recycle/metal/trash-can.PNG",
    },
};